codetechies/codepoint/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name="home"),
    path('course/<str:slug>/', views.course_informations, name="cour"),
    path('course1/<str:slug>/', views.testing_de, name="cour1"),
]

codetechies/codetechies/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('codepoint.urls')),
]

codetechies/codepoint/models.py
from django.db import models

# Create your models here.


class Course_Category(models.Model):
    course_name = models.CharField(
        max_length=200, default=None, null=True, blank=True)
    slug = models.CharField(max_length=50, null=False, unique=True)
    desc = models.CharField(max_length=50, null=False)
    date = models.DateTimeField(auto_now=True)
    resource = models.FileField(upload_to='files/resource')
    image = models.ImageField(upload_to='static/image')

    def __str__(self):
        return self.course_name


class Course_Information(models.Model):
    title = models.CharField(max_length=100, null=True)
    course = models.ForeignKey(
        Course_Category, on_delete=models.CASCADE, null=True)
    course_cat_id = models.CharField(max_length=100, null=True)
    course_content = models.TextField(
        blank=True, max_length=10000, null=True, default="")

    s_no = models.IntegerField(null=True)

    def __str__(self):
        return self.title


class testing(models.Model):
    tes_id = models.ForeignKey(Course_Information, on_delete=models.CASCADE)
    slug = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.tes_id.title

codetechies/codepoint/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Create your views here.

from .models import *


def index(request):

    global content
    course_category_obj = Course_Category.objects.all()

    content = {
        'course_category_obj': course_category_obj,
    }

    return render(request, 'index.html', context=content)


def course_informations(request, slug):

    fetch_dtls = Course_Category.objects.get(slug=slug)

    s_no = request.GET.get('serial_no')

    if s_no is None:
        s_no = 1
    try:
        video = Course_Information.objects.get(course=fetch_dtls, s_no=s_no)
        request.session['name'] = video.title
        print(request.session['name'])

    except:
        return redirect('home')
    context = {
        'fetch_dtls': fetch_dtls,
        'f': video,
        'content': content.get('course_category_obj')


    }

    return render(request, 'html_tutorial.html', context=context)


def testing_de(request, slug):

    c = request.session.get('name')
    return render(request, 'f.html', {'context': c, "slug": slug})

codetechies/codepoint/templates/base.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
  <body>
        <header class="p-3 mb-1 border-bottom shadow-lg">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-light text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url "home" %}" class="nav-link fs-5 px-3 link-light abc">Home</a></li>
          <li><a href="#" class="nav-link fs-5 px-3 link-light abc">Free Lancing</a></li>
          <li><a href="#" class="nav-link fs-5 px-3 link-light abc">Tutorials</a></li>
          <li><a href="#" class="nav-link fs-5 px-3 link-light abc">Blogs</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="dropdown text-end dropdown-hover">
          <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" data-bs-hover="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
            <li><a class="dropdown-item" href="#">New project...</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
    {% block content %}{% endblock content %}

    <footer>
  <p>Footer</p>
</footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

codetechies/codepoint/templates/f.html
{% block content %}
{% include "html_tutorial.html" %}
{% endblock content %}

{% comment %} 
{% if slug=='{{p}} %}
this is html
{% endif %} {% endcomment %}
{% comment %} {{c}}
{{p}}
{% if c == p %}
{% include "h.html" with c=p %}
{% endif %} {% endcomment %}

codetechies/codepoint/templates/h.html
{% comment %} {% block g %}
{% if request.session.name %}

{% endif %}
{% endblock g %} {% endcomment %}

codetechies/codepoint/templates/html_tutorial.html
{% extends "base.html" %}

{% include "index.html" %}
{% load test %}
{% load static %}
{% block title %}{{f.course_name}}{% endblock title %}

{% block content %}
<div class="navbar-heading py-3 d-flex justify-content-evenly sticky-top">
    {% for co_object in content %}
        
            <a href="/course/{{co_object.slug}}" class="nav-link fs-6 px-3 link-light a_link">{{co_object.course_name}}</a>
    
    {% endfor %}
</div>

<section class="d-flex justify-content-center bg-secondary" >
  <h2 class="text-uppercase my-3 fs-1 " >{{fetch_dtls.course_name}} Tutorial</h2>
</section>

<section>
  <nav>
    <ul>
      <li>
        <img src="{% static 'images/html5.jpg' %}" alt="" width=100% height=193 class="rounded rounded-5">
      </li>
    </ul>
    <ul class="list-group">
      {% for i in fetch_dtls.course_information_set.all %}
        {% comment %} <li><a href = "../../course1/{{i.title}}" %} class="list-group-item list-group-item-action fs-5" >{{i.title}}</a></li> {% endcomment %}
        <li><a href="?serial_no={{i.id}}" class="list-group-item list-group-item-action fs-5" >{{i.title}}</a></li>
      {% endfor %}
      
     
    </ul>
  </nav>
  
  <article>
   
   <div class="example">
     {% autoescape off %}
     {{f.course_content}}
     {% endautoescape %}
   </div> 
  <div id="myDiv" class="ms-3 mt-4" style="display:none;">
      
      <h1 id="myh1">This is a heading</h1>
      <p >Hello World!</p>
  </div>
   </article>
</section>

<script>
const nodeList = document.querySelectorAll(".example p");
for (var i = 0; i < nodeList.length; i++) {
  nodeList[i].setAttribute('id','tab'+i);
  nodeList[i].setAttribute('class',"ass add");
  
}
c =  document.getElementById('tab6')
c.text = "<html><head></head><body>hsdg</body>"

function loadDoc() {
  {% comment %} alert("hello") {% endcomment %}
  const xhttp = new XMLHttpRequest();
  xhttp.onload = function() {
    document.getElementById("demo").innerHTML =
    this.responseText;
  }
  alert("{{f.title}}")
  xhttp.open("GET", "../../course1/{{f.title}}");
  xhttp.send();
}
{% comment %}  {% endcomment %}
{% comment %} function myFunction() {
  
  var x = document.getElementById("myDiv");
  console.log(x);
  if (x.style.display === "none") {
  
    x.style.display = "block";

  } else {
    x.style.display = "none";
  }
}    {% endcomment %}





</script>
{% endblock content %}

codetechies/codepoint/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}

<div class="navbar-heading py-3 d-flex justify-content-evenly sticky-top">
    {% for co_object in course_category_obj %}
        
            <a href="/course/{{co_object.slug}}" class="nav-link fs-6 px-3 link-light a_link">{{co_object.course_name}}</a>
    
    {% endfor %}
</div>
<section id="hero" class="d-flex align-items-center sec">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1 aos-init aos-animate" data-aos="fade-up" data-aos-delay="200">
          <h1>Better Solutions For Your Business</h1>
          <h2>We are team of talented designers making websites with Bootstrap</h2>
          <div class="d-flex justify-content-center justify-content-lg-start">
            <a href="#about" class="btn-get-started scrollto">Get Started</a>
            <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img aos-init aos-animate" data-aos="zoom-in" data-aos-delay="200">
          <img src="{% static '/images/hero-img.png' %}" class="img-fluid animated" alt="">
        </div>
      </div>
    </div>

  </section>

<section id="clients" class="clients section-bg">
      <div class="container ">

        <div class="row aos-init aos-animate" data-aos="zoom-in">

          <div class="col-lg-2 col-md-4 col-6 d-flex align-items-center justify-content-center">
            <h2>Django</h2>
          </div>

        </div>
      </div>
    </section>
{% endblock content %}